import logging
from src.configurations.constants import ALL_TAGS, AnswerTypeEnum, QuestionnaireTagEnum
from src.extras.PhpSerializer import decode_php_serialized
from src.models.wp_forms import WPForm
from src.models.wp_fields import WPField
from src.models.questionnaires import Questionnaire
from src.schemas.dependencies import Dependencies, ShowHideEnum, AllAnyEnum, Condition, ConditionOperatorEnum
from src.schemas.questions import AnswerOption, QuestionBase
from src.schemas.questionnaires import QuestionnaireCreateWithQuestions, QuestionnaireCreateWithQuestionsNew

logger = logging.getLogger(__name__)


class WPToQuestionnaireAdapter:
    """Convert a WordPress form and its fields into an internal questionnaire command.

    Existing questionnaires produce a new explicit version. Previously unseen
    questionnaires use the command whose identifier is generated by PostgreSQL.
    """

    def adapt(
        self, wp_form: WPForm, existing_questionnaire: Questionnaire | None, new_hash: str
    ) -> QuestionnaireCreateWithQuestions | QuestionnaireCreateWithQuestionsNew:

        # Preserve the source field order while adapting each field.
        questions: list[QuestionBase] = []
        for field in wp_form.fields:
            question = QuestionBase(
                question=field.name or "",
                question_order=field.field_order,
                answer_options=self._decode_answer_options(field),
                answer_type=self._decode_answer_type(field),
                dependencies=self._decode_dependencies(field),
                wordpress_id=field.id,
            )
            questions.append(question)

        if existing_questionnaire:
            return QuestionnaireCreateWithQuestions(
                questionnaire_id=existing_questionnaire.questionnaire_id,
                questionnaire_version=existing_questionnaire.questionnaire_version + 1,
                questionnaire_name=wp_form.name or "",
                wordpress_id=wp_form.id,
                is_active=True,
                tags=self._extract_tags(wp_form),
                questionnaire_hash=new_hash,
                questions=questions,
            )

        return QuestionnaireCreateWithQuestionsNew(
            questionnaire_name=wp_form.name or "",
            wordpress_id=wp_form.id,
            is_active=True,
            tags=self._extract_tags(wp_form),
            questionnaire_hash=new_hash,
            questions=questions,
        )

    def adapt_all(
        self, data: list[tuple[WPForm, Questionnaire | None, str]]
    ) -> list[QuestionnaireCreateWithQuestions | QuestionnaireCreateWithQuestionsNew]:
        return [
            self.adapt(wp_form, existing_questionnaire, new_hash) for wp_form, existing_questionnaire, new_hash in data
        ]

    @staticmethod
    def _extract_tags(form: WPForm) -> list[QuestionnaireTagEnum]:
        """Extract normalized questionnaire tags from the WordPress form key."""
        form_key = (form.form_key or "").lower()
        return [QuestionnaireTagEnum(tag) for search_tag, tag in ALL_TAGS if search_tag in form_key]

    @staticmethod
    def _as_text(value: object, *, default: str = "") -> str:
        if isinstance(value, str):
            return value
        if isinstance(value, int | float | bool):
            return str(value)
        return default

    @staticmethod
    def _decode_answer_options(field: WPField) -> list[AnswerOption]:
        """Decode Formidable options without losing their display labels."""

        raw = field.options
        if not raw:
            return []

        try:
            options = decode_php_serialized(raw)
            if isinstance(options, dict):
                options = list(options.values())
            if not isinstance(options, list):
                return []

            result = []
            for item in options:
                if not isinstance(item, dict) or "value" not in item:
                    continue
                value = item["value"]
                label = WPToQuestionnaireAdapter._as_text(item.get("label", value))
                result.append(AnswerOption(label=label, value=value))
            return result

        except Exception as error:
            logger.error("Failed to decode answers for field %s: %s", field.id, error)
            return []

    @staticmethod
    def _decode_answer_type(field: WPField) -> AnswerTypeEnum:
        """Convert a Formidable field type, falling back to TEXTAREA when unknown."""

        # Formidable stores lowercase names while the internal enum uses uppercase values.
        t = (field.type or "").upper()
        if t not in AnswerTypeEnum.__members__:
            logger.warning("Unknown field.type '%s' for field %s, defaulting to TEXTAREA", t, field.id)
            t = "TEXTAREA"
        return AnswerTypeEnum(t)

    @staticmethod
    def _decode_dependencies(field: WPField) -> Dependencies:
        """Decode Formidable field options into normalized visibility dependencies."""
        raw = field.field_options or ""
        try:
            data = decode_php_serialized(raw)
        except Exception as error:
            logger.error("Failed to decode dependencies for field %s: %s", field.id, error)
            # A malformed optional dependency block must not discard the entire questionnaire.
            return Dependencies(show_hide=ShowHideEnum.SHOW, all_any=AllAnyEnum.ALL, conditions=[])

        if not isinstance(data, dict):
            return Dependencies()

        try:
            show_hide = ShowHideEnum(WPToQuestionnaireAdapter._as_text(data.get("show_hide"), default="SHOW").upper())
        except ValueError:
            logger.warning("Unknown show/hide mode in field %s; defaulting to SHOW", field.id)
            show_hide = ShowHideEnum.SHOW

        try:
            all_any = AllAnyEnum(WPToQuestionnaireAdapter._as_text(data.get("any_all"), default="ALL").upper())
        except ValueError:
            logger.warning("Unknown any/all mode in field %s; defaulting to ALL", field.id)
            all_any = AllAnyEnum.ALL

        # Formidable represents conditions as three parallel arrays.
        flds = data.get("hide_field", [])
        conds = data.get("hide_field_cond", [])
        opts = data.get("hide_opt", [])

        conditions: list[Condition] = []
        for fld, cond, val in zip(flds, conds, opts):
            try:
                cond_enum = ConditionOperatorEnum(cond.upper())
            except ValueError:
                logger.warning("Unknown condition operator '%s' in field %s", cond, field.id)
                cond_enum = ConditionOperatorEnum.EQUAL
            conditions.append(
                Condition(
                    field_id=int(fld),
                    condition=cond_enum,
                    value=WPToQuestionnaireAdapter._as_text(val),
                )
            )

        return Dependencies(show_hide=show_hide, all_any=all_any, conditions=conditions)
